---
title: "ADS503 Finals Project"
output: html_document
date: "2023-05-31"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(corrplot)
```

```{r}
setwd("/Users/amyou/Desktop")
library(readr)
brain_stroke=read_csv("healthcare-dataset-stroke-data.csv")
brain_stroke
```
```{r}
#removing null values
brain_na=brain_stroke[-which(brain_stroke$bmi=="N/A"),]
```

```{r}
#Types of data
str(brain_stroke)
#Dimension of the data
dim(brain_stroke)
```
```{r}
#Change from character to factor to numeric
library(dplyr)
brain_stroke_fac<- brain_na %>% mutate_if(is.character, as.factor)
brain_stroke_num <- brain_stroke_fac %>% mutate_if(is.factor, as.numeric)
brain_stroke_num
```
```{r}
#identify outliers using boxplot
library(ggplot2)
par(mfrow = c(1, 3))
for (i in 1:ncol(brain_stroke_num)) {boxplot(brain_stroke_num[ ,i], xlab = names(brain_stroke_num[i]),
                           main = paste(names(brain_stroke_num[i]), "Boxplot"))}
```
```{r}
#check for duplicates
sum(duplicated(brain_stroke_num))
```

```{r}
#correlation test
correlation <- cor(brain_stroke_num)
dim(correlation)
corrplot(correlation, order = "hclust")
correlation
```
```{r}
#dropping columns
brain_drop=subset(brain_stroke_num, select=-c(id, Residence_type, gender, bmi))
brain_drop
```
```{r}
#correlation test on brain_drop
correlation_drop <- cor(brain_drop)
dim(correlation_drop)
corrplot(correlation_drop, order = "hclust")
correlation_drop
```
```{r}
#skewness
library(moments)
skewness(brain_drop)
```
```{r}
summary(brain_drop)
```
```{r}
#histogram of the variables
library(Hmisc)
hist.data.frame(brain_drop)
hist(brain_drop$ever_married)
hist(brain_drop$hypertension)
hist(brain_drop$heart_disease)
hist(brain_drop$stroke)
```

